name: eslint,tsc

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [develop, feature/*, bugfix/*]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint_and_typecheck:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci-skip') }}
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # Install modules
      - name: Install modules
        run: yarn install

      - name: tsc
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn tsc
      
      - name: eslint
        run: yarn lint
      
      - name: lint test result
        uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: dante01yoon
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ACTION_BOT }}
        if: always()